### ISSUE TITLE
connect ECONNREFUSED

### ISSUE THREAD

**Issue by itayme** [molnarg/node-http2#102]
Hey, upon creating the server with node ./example/server.js in one cmd, trying to connect on other cmd with: node ./example/client.js 'https://127.0.0.1:8080/server.js' and receiving the following error:
Error: connect ECONNREFUSED
at exports._errnoException <util.js:746:11>
at TCPConnectWrap.afterConnect [as oncomplete] <net.js:983:19>

Is this the correct way? Opening a server on one cmd and trying to connect on the other?

Any ideas?

**Comment by molnarg** [comment]
Yeah this is the correct way. It seems that the TCP connection is not correctly built up, because the target port is not open. Could you have a look at it in Wireshark?

**Comment by nwgh** [comment]
I don't get an ECONNREFUSED, though I do (with node v5.3.0) get an error about a self-signed certificate in use. That might be worth fixing, but as a separate issue.
