### ISSUE TITLE
How to generate `key` and `crt` files

### ISSUE THREAD

**Issue by IonicaBizau** [molnarg/node-http2#105]
How to generate the `key` and `crt` files? Or where do I get them from?

```js
...
  key: fs.readFileSync('./example/localhost.key'),
  cert: fs.readFileSync('./example/localhost.crt')
...
```

**Comment by molnarg** [comment]
Example keys are included in the example directory! What error you get and where do you try to run the example server? It should work without any problem with the included cert and key.

**Comment by IonicaBizau** [comment]
I started the server process (`node server.js`) and then I did `curl localhost:8080`. No response comes, nor in `curl` nor in browser.

However, my question is where did you get these files from? How to generate such files?

**Comment by molnarg** [comment]
These are standard PEM key and crt files. See the first few paragraphs of the node TLS docs for example: https://nodejs.org/api/tls.html or this tutorial: http://www.akadia.com/services/ssh_test_certificate.html

When testing in browser or curl, use HTTPS:// since the example server server http2 over tls. Second, try getting the server.js file. There is no index.html to get from the example server.

**Comment by IonicaBizau** [comment]
Thanks! So with `openssl` we can generate them.

When I provide the `https` protocol I get an error:

```sh
$ curl https://localhost:8080
curl: (60) SSL certificate problem: self signed certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

![image](https://cloud.githubusercontent.com/assets/2864371/6705399/47403a64-cd5d-11e4-860f-6d4e08cbb2cc.png)

**Comment by molnarg** [comment]
Yeah, this is a self signed cert, and maybe also expired, so it's time to regenerate it :/ How about curl with the `--insecure` option? Like this: `curl -k https://127.0.0.1:8080/server.js` It works for me, however this falls back to HTTP1 as seen in the server log:

```
mg-mac:node-http2 mg$ HTTP2_LOG=info node ./example/server.js
09:18:28.547Z  INFO server/http: Creating HTTP/2 server over TLS
09:18:28.557Z  INFO server/http: Listening for incoming connections (on=8080)
09:18:30.959Z  INFO server/http: Falling back to simple HTTPS (client=127.0.0.1:52118, protocol=false, SNI=false)
```

**Comment by molnarg** [comment]
My curl is probably not up to date enough to support HTTP2.

**Comment by IonicaBizau** [comment]
@molnarg It works fine with the `-k` option.

I generated with `openssl` new `key` and `crt` files (replacing the old ones) and I still get the error above. What could be the reason?

**Comment by molnarg** [comment]
Self signed cert, or you generated a CA then a cert? If the former, I'd try the latter, and add the CA to the list of root CAs. But btw, you would need a real, valid cert if you want to use http2 on the web...

**Comment by IonicaBizau** [comment]
*a real, valid cert if you want to use http2 on the web* - is this paid or...?

**Comment by molnarg** [comment]
Yes. But there are a few alternatives, see https://www.startssl.com/ and https://letsencrypt.org/ . I will close this ticket now. I suggest you to have a valid cert first and try with that. The demo server and cert is only for experimentation.

**Comment by IonicaBizau** [comment]
@molnarg Thanks a lot! :+1:
