### ISSUE TITLE
Chrome SPDY indicator plugin does not see the endpoint as HTTP2

### ISSUE THREAD

**Issue by molnarg** [molnarg/node-http2#106]
Hitting an endpoint from chrome with the SPDY indicator extension doesn't indicate the endpoint is http2 (via the blue lightning bold).

**Comment by jinjor** [comment]
Is this a bug?
Chrome currently does not support 'h2' protocol, so negotiation is probably failed.
Chrome Canary works correctly.

**Comment by molnarg** [comment]
Yeah, you're right. I've just tested it in canary and works like a charm. Chrome stable wants to negotiate h2-14 while node-http2 supports the final standard.
