### ISSUE TITLE
Consider bumping required node version to >= 0.12

### ISSUE THREAD

**Issue by todesschaf** [molnarg/node-http2#108]
Since with 0.12, we can finally enforce TLS cipher suite ordering, and thus make it so we actually speak appropriate h2-approved cipher suites with well-behaved peers, I think we should consider bumping our required version to that so we can be spec-compliant.

(Sadly, that update doesn't ensure total compatibility, as it doesn't have APIs to ensure we are using an appropriate cipher if we're talking to a misbehaving peer, nor does it have an API to choose or validate the TLS version in use. It's still a step in the right direction, though.)

@molnarg, what do you think?

**Comment by molnarg** [comment]
As node 0.12 is officially released now, I completely support bumping the required version!
