### ISSUE TITLE
No response from server

### ISSUE THREAD

**Issue by jussi-kalliokoski** [molnarg/node-http2#125]
Trying out the example with `HTTP2_PLAIN=true node examples/server.js` (as well as trying out in my own experiment) and opening `http://localhost:8080/server.js` in Chrome just queues a new download that never finishes. If I add a `console.log` in the beginning of `onRequest`, nothing gets logged.

![screen shot 2015-06-30 at 15 33 58](https://cloud.githubusercontent.com/assets/547186/8430894/a8ad0692-1f3d-11e5-8073-4da27094c7f1.png)

I'm on node ~~v0.12.0~~ v0.12.5 now.

**Comment by timmckenzie** [comment]
Chrome does not support clear text HTTP2. In fact, all of the major browsers said that they would not support clear text HTTP2.  There is a section in [this blog post](http://daniel.haxx.se/blog/2015/03/06/tls-in-http2/) about it.  As to why it just shows a "starting..." document I don't know.  I would think that it is a bug in Chrome.

If you want to make requests to your server to see it work, you should use ```HTTP2_PLAIN=true node examples/client.js```. [NG HTTP 2](https://nghttp2.org/) is also an option for making plain text H2 requests.

**Comment by jussi-kalliokoski** [comment]
Ahh, that explains it, thanks! Works like a charm with encryption!
