### ISSUE TITLE
Is ALPN supported with this module on io.js?

### ISSUE THREAD

**Issue by domenic** [molnarg/node-http2#126]
The necessary changes are in, but does http2 need to do anything extra to support it? The readme is unclear.

**Comment by nwgh** [comment]
I just ran a quick test, and though I don't know what, it does appear that there is something else that is required to use ALPN on io.js. This will take some investigation.

**Comment by stevenvachon** [comment]
Added to Node.js v5: https://github.com/nodejs/node/pull/2564

**Comment by mikeal** [comment]
This should be re-named, and hopefully prioritized now that Node.js v5 has ALPN :)

**Comment by nwgh** [comment]
Did yet another quick test with node 5.3.0, and ALPN is negotiated just fine between Firefox (which sends both ALPN and NPN) and node-http2.
