### ISSUE TITLE
Server push config file

### ISSUE THREAD

**Issue by LaurentGoderre** [molnarg/node-http2#127]
Hi,

Pardon my ignorance but I was wondering if anyone considered creating a configuration file for server push where you could have , for example, a URL or a regex for a URL and the resources to push with that URL. It would be nice to have a solution for push that did not require any server-side code.

**Comment by nwgh** [comment]
I think this sounds more like something that would belong in a higher-level library, like express (whenever it works with node-http2). Given there's no real configuration for serving URLs other than to write a giant if/else (or file lookup, or something else similar) directly with node-http2, we're a bit low layer to be automatically pushing things.
