### ISSUE TITLE
 download popup box shows when accessing urls built by http2

### ISSUE THREAD

**Issue by xinyuanyu** [molnarg/node-http2#138]
Here is the code i tested 

```javascript
var options = {
  plain: true
};

require('http2').raw.createServer(options, function(request, response) {
  response.end('Hello world!');
}).listen(8085);
```

when I access 8085 port with http protocol in chrome, there wolud be a download popup box, 
and the content type is document.

the env is : 
node : v0.12.0
http2: 3.2.0

Any ideas ?

**Comment by timmckenzie** [comment]
I believe that you are seeing this.

https://github.com/molnarg/node-http2/issues/125

**Comment by nwgh** [comment]
Yes, that sounds like it would be #125, or some issue being caused by not sending a Content-Type header with the response. Either way, not a bug in the library.

**Comment by xinyuanyu** [comment]
Yeah, same issue listed in #125, thanks for your help.
