### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by cconcolato** [molnarg/node-http2#139]
The documentation hosted in the gh-pages branch has broken links/
* http://molnarg.github.io/node-http2/doc/endpoint.html
* http://molnarg.github.io/node-http2/doc/stream.html

and I think an outdated link:
* https://github.com/molnarg/node-http2-protocol

**Comment by nwgh** [comment]
Yes, the documentation needs regenerated (and quite possibly scanned for other bad links)

**Comment by akc42** [comment]
It still does, nearly 5 months later

**Comment by nwgh** [comment]
Docs have been updated.
