### ISSUE TITLE
Accept session resumption IDs

### ISSUE THREAD

**Issue by bjb568** [molnarg/node-http2#150]
With the https module I could do this to accept the session resumption IDs that are automatically set:

	var sslSessionCache = {};
	server.on('newSession', function(sessionId, sessionData, callback) {
		sslSessionCache[sessionId] = sessionData;
		callback();
	});
	server.on('resumeSession', function (sessionId, callback) {
		callback(null, sslSessionCache[sessionId]);
	});

This module also sets IDs but doesn't seem to accept them. Is there a way to make this work? I would prefer to have it fire the same events as the https module.

**Comment by nwgh** [comment]
Yes, it would be good to enable session resumption with h2. Putting this in the backlog.
