### ISSUE TITLE
Client certificate feature is not implemented

### ISSUE THREAD

**Issue by arashTaher** [molnarg/node-http2#152]
Apparently there's no way to authenticate clients with certificates. Which means that there are no equivalent to TLS [authorized](https://nodejs.org/api/tls.html#tls_tlssocket_authorized) and [getPeerCertificate](https://nodejs.org/api/tls.html#tls_tlssocket_getpeercertificate_detailed). Am I right ?

**Comment by Peppar** [comment]
It seems that the http2 version installed by npm is not the latest and does not assign request.socket correctly (request.socket is a Stream). With the current version on github, request.socket is a TLSSocket and you can use getPeerCertificate().

**Comment by arashTaher** [comment]
Using latest version solved the problem. Thanks for your answer @Peppar 
I hope they update the npm package sooner, it's nine month old
