### ISSUE TITLE
Question on response end and also PUSH_PROMISE frames

### ISSUE THREAD

**Issue by dman777** [molnarg/node-http2#154]
Reading [from this tutorial](https://www.igvita.com/2013/06/12/innovating-with-http-2.0-server-push/) don't you have to give the `<script src="/main.js"></script>'` in the end repsonse? 

for Example:

```javascript
spdy.createServer(options, function(req, res) {
  // push JavaScript asset (/main.js) to the client
  res.push('/main.js', {'content-type': 'application/javascript'}, function(err, stream) {
    stream.end('alert("hello from push stream!")');
  });

  // write main response body and terminate stream
  res.end('Hello World! <script src="/main.js"></script>');
}).listen(443);
```

I don't see that in the [repo server.js example](https://github.com/molnarg/node-http2/blob/master/example/server.js#L22)

Also, does `node-http2` send `PUSH_PROMISE frames`?

**Comment by akc42** [comment]
Just came across this.  If you look at the example in the repo its piping the filestream.  That generates the stream end for you.

**Comment by nwgh** [comment]
To answer the second question, of course node-http2 will send PUSH_PROMISE frames - that's how push is implemented.

Also, regarding adding the markup in the response - for regular web browsing, yes, that's required for push to do any good. However, there are other uses of push, such aswebpush (see https://tools.ietf.org/wg/webpush/) which don't have the same requirements.
