### ISSUE TITLE
Keeps returning ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by Py64** [molnarg/node-http2#156]
My web server (HTTPjs) keeps returning ERR_CONNECTION_CLOSED on HTTP/2.0 over TLS, and allows to download file over plain (but doesn't gives access to file, leaving client in loop).

I tried with piping but nothing works.

Edit: I switched to node-spdy.

**Comment by mhoffmeyerDC** [comment]
I'm able to reproduce this with the example from the readme using release 3.2.0 - same code works OK with the latest commit from the repo.

**Comment by Piefayth** [comment]
Yes, the current npm package is seemingly non-functional. I just discovered this as well.

**Comment by nwgh** [comment]
New release coming today, closing this mhoffmeyerDC indicates it works fine with the latest from the repo. If the issue persists with the new release, please open a new bug with more details and STR, thanks.

**Comment by mhoffmeyerDC** [comment]
This would still be broken for people installing from NPM as it uses the most recent tag. Time for a new release?

**Comment by nwgh** [comment]
Hence the "New release coming today" in my previous comment. 3.3.0 is now available via npm.
