### ISSUE TITLE
http2.Server.address missing API

### ISSUE THREAD

**Issue by felicienfrancois** [molnarg/node-http2#157]
With `https`, I Open a server on a random port with the following snippet:
```
var server = require('https').createServer(myOptions);
server.listen(function() {
    console.log("Server started on port "+server.address().port);
});
```

With `http2`, I get the following error:
```
server.address is not a function
```

This should be either implemented or added to missing API's.
Then, What is the recommended way to get the port of a http2 server opened on a random port?

**Comment by casalot** [comment]
@felicienfrancois, did you manage to get a workaround for the `server.address is not a function` issue?

**Comment by felicienfrancois** [comment]
@casalot `server._server.address()` seems to do the job :)

**Comment by casalot** [comment]
Thanks @felicienfrancois , but where do i add/change that?

**Comment by felicienfrancois** [comment]
If you want to make a pull request, you should add the address method to the `Server` prototype near there https://github.com/molnarg/node-http2/blob/master/lib/http.js#L535

If you want to use a workaround in your code, you can either locate `.address ()` usages in your code and insert `._server` before or add something like this on top of your code:
```
var http2 = require('http2');
http2.Server.prototype.address = function() {
    return this._server.address.apply(this, arguments);
}
```

**Comment by casalot** [comment]
@felicienfrancois, you're suggestions got rid of the `server.address is not a function` error, but now I'm facing this:`self.info.address = address.address;
TypeError: Cannot read property 'address' of null`

**Comment by felicienfrancois** [comment]
You can try this:
```
var http2Server = Http2.createServer(sslOptions);
http2Server.address = function() {
    return this._server.address.apply(this, arguments);
};
server.connection({
  listener: http2Server,
  host: apiHost,
  port: apiPort,
  tls: true,
  routes: {
    cors: true
  }
});
```

**Comment by casalot** [comment]
Nope. Same error.

The only way I got this working was by changing hapi's `lib/connection.js`:
from:
```javascript
var address = self.listener.address();
```
to:
```javascript
var address = self.listener._server.address();
```
Not ideal, as I'll have to manually update this every time I upgrade hapi, but at least it's working for now.

Thanks for the help, @felicienfrancois!
