### ISSUE TITLE
HPE_INVALID_CONSTANT error in client

### ISSUE THREAD

**Issue by mihai1voicescu** [molnarg/node-http2#188]
Hello,

When I try to access Apple's APN I receive the following message in the event 'error' of the request

`[root@mihaivo http2]# node ./example/client.js 'https://api.development.push.apple.com/3/device/00fc13adff785122b4ad28809a3420982341241421348097878e577c991de8f0'
{ [Error: Parse Error] bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }`

HPE_INVALID_CONSTANT means the start of the request is seen as invalid(https://github.com/nodejs/node-v0.x-archive/issues/4863).
Any ideas on why this is happening?

Kind regards,
Mihai

**Comment by mihai1voicescu** [comment]
It appears the problem is generated by the ALPN support. Upgrading node to 5.x solves this problem.

**Comment by mihai1voicescu** [comment]
This should be specified on the front page or upgrade the node version in the package.json

**Comment by nwgh** [comment]
That specification is right there in the README.
