### ISSUE TITLE
Best node.js version for this module

### ISSUE THREAD

**Issue by tuanhm93** [molnarg/node-http2#211]
Hi all, i'm using this module to implement push notification on iOS platform, but sometimes i see that i have sent 1000 requests but only get responses less than of them. Now my solution is set a function call after one minutes to check if finish or not. And i realise that version of node.js is the problem. 6.3.0 always have problem. So i wanna ask if someone have the same problem with me, or any suggest for me about this problem. Thanks so much, sorry cause my english not good :(

**Comment by nwgh** [comment]
Looking at some other bugs we have, it would appear that node 6.3.0 has caused some issues. Whether it's node-http2 bugs that were just exposed by node 6.3.0, or bugs in node 6.3.0 is to be determined. For now, I would stick with node 6.2.x or the LTS (currently 4.4.7)

**Comment by q2dg** [comment]
Just wondering if could be possible merging this module into official Nodejs' "http" one...
