### ISSUE TITLE
`request()` does not actually have `plain` option

### ISSUE THREAD

**Issue by thammi** [molnarg/node-http2#212]
The API page claims that `request()` has the additional `plain` option. This is not true as `request()` is actually `requestTSL()` which overwrites `plain` to `false` (see [here](https://github.com/molnarg/node-http2/blob/master/lib/http.js#L637)). Raw requests are supported through `exports.raw` which does no seem to be documented at all.

**Comment by nwgh** [comment]
Indeed, the docs need fixed up & regenerated (which I am, obviously, too lazy to do). Dupe of #139
