### ISSUE TITLE
TypeError :parser.incoming._addHeaderLines is not a function 

### ISSUE THREAD

**Issue by jetpower0130** [molnarg/node-http2#226]
Hi, I'm working  http2 with express.js on my server. It good to work when I use firefox brower to connect the server, but it can't connect when I use chrome to connect, the server side show the following information :
![http2problem](https://cloud.githubusercontent.com/assets/23101371/20593012/83cb0488-b26b-11e6-8439-8ef6c715c121.png)

And the server closed immediately. What's problem with me? Can someone help me to solved it.

Tools version:
express.js : 4.14
node-http2 : 3.3.6 
firefox : 50.0
chrome : 54.0.2840.99 m

**Comment by RohitRane** [comment]
I am getting this issue too. Why is this issued closed without any solution or discussion?

**Comment by NESL-AllenYang** [comment]
I am getting this issue too. What's problem with me? Can someone help me to solved it.
