### ISSUE TITLE
Project dead? 

### ISSUE THREAD

**Issue by 75lb** [molnarg/node-http2#248]
I'm assuming so. Shame, because PRs which solve the main issues are ready and waiting to land. 

Does anyone have a maintained fork they can recommend?

**Comment by akc42** [comment]
Nodejs itself is very close to landing a native http2 server in the core of node.  See https://github.com/nodejs/http2

In the meantime, I took a fork of this, added the PRs that made sense for me and am using that until the new server lands.  You are welcome to use it, but I am not really maintaining it see https://github.com/akc42/node-http2

**Comment by 75lb** [comment]
i saw your fork, thanks - yes it has one of the crucial PRs on it but not others that I need.. I'll fork myself for the time being. 

I imagine the node module will land eventually but we'll still need a backup module to support users that don't have bleeding-edge node installed. 

Seems to me general interest in HTTP2 is modest at best. As people keep saying, H2 is "no silver bullet".
