### ISSUE TITLE
Tracing http2 on the wire

### ISSUE THREAD

**Issue by seti123** [molnarg/node-http2#96]
It would be nice if http2 could be added to node_pcap  - could we get some support for it? 
What would be the best way to use some parts of this project - is there a streaming interface where decoded packets could be injected and decoded?

**Comment by molnarg** [comment]
We have very nice streaming interfaces to interact with anything that is stream, and a modular, stream based architecture. See this for an overview: https://github.com/molnarg/node-http2/blob/master/lib/protocol/index.js

There's a difference between an endpoint playing an active role (receives and sends packets from/to the other endpoint), and when there's two endpoint and we watch them communicate. We primarily support the former use case, but supporting the second one should be doable with reusing some parts of node-http2, like the deserializer, decompressor and maybe other parts (I'm pretty sure the stream state machines would have to be rewritten).

Although I don't think this is in scope for this project, the needed code should live somewhere else, maybe node_pcap or a standalone project.
